# Generated by Django 3.2.23 on 2024-03-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interiordesign', '0002_remove_design_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('location', models.CharField(max_length=254)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_project', to='interiordesign.design')),
            ],
        ),
    ]
