# Generated by Django 3.2.23 on 2024-03-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='body',
            new_name='message',
        ),
    ]
