# Generated by Django 3.2.23 on 2024-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_product',
            field=models.BooleanField(default=False, verbose_name='Top Product'),
        ),
    ]
